In [5]:
import pandas as pd 

df_1 = pd.read_csv('data/24_25_survey.csv')
df_2 = pd.read_csv('data/23_24_survey.csv')

In [ ]:
#hello

In [6]:
df_1.head()

,Timestamp,First and Last Name (entry for gift card raffle),What is your Class Status?,How many semesters have you lived on campus at Grand View?,Are you currently 21 or older,Do you participate on a Grand View athletic team?,Which Residence Hall did you live in during the fall semester?,What floor did you live on during the fall semester?,Please read the following statements regarding you fall semester RA and rate them. [It is easy to get in contact with my RA],Please read the following statements regarding you fall semester RA and rate them. [I am comfortable talking with my RA],...,Please read the following statements regarding the outcome of living on campus and rate them. [I am better able to lead others because I have lived on campus],Please read the following statements regarding the outcome of living on campus and rate them. [I am better able to take responsibility for my actions because I have lived on campus],Please read the following statements regarding the outcome of living on campus and rate them. [Living on campus had a positive impact on my academic success],Please read the following statements regarding the outcome of living on campus and rate them. [Living on campus has created a sense of belonging at Grand View University],What are the main benefits of living on campus?,What do you enjoy most about living on campus?,What do you dislike about living on campus?,How would you rate your overall satisfaction in regards to living on campus?,Please provide any additional feedback on the Housing Sign-up Process,"Please type your name below to be entered into a gift card drawing for a chance to win a gift card to Target, Krispy Kreme, Taco Bell, and more! There are 5 chances to win!"
0,3/27/2025 14:35:10,Scott Pengelly,Senior,1-2 semesters,Yes,Yes,L Apartments,4th floor,Neutral,Neutral,...,Neutral,Neutral,Neutral,Neutral,No benefits to living on campus,NaN,NaN,Dissatisfied,NaN,Scott Pengelly
1,3/27/2025 14:37:01,Carley Janssen,Sophomore,3-4 semesters,No,Yes,Hull Apartments,1st floor,Strongly Agree,Strongly Agree,...,Neutral,Neutral,Neutral,Neutral,"Proximity to classes, Live within a community ...",NaN,NaN,Satisfied,NaN,Carley Janssen
2,3/27/2025 14:37:02,Adelynne Peterson,Junior,3-4 semesters,No,No,Hull Suites,4th floor,Agree,Agree,...,Strongly agree,Strongly agree,Strongly agree,Strongly agree,"Proximity to classes, Live within a community ...",NaN,NaN,Satisfied,NaN,Adelynne Peterson
3,3/27/2025 14:38:25,NaN,Freshman,1-2 semesters,No,Yes,Langrock Suites,2nd floor,Strongly Agree,Strongly Agree,...,Neutral,Neutral,Neutral,Agree,"Proximity to events/activities, On-Campus Livi...",How close it is,Expensive,Satisfied,NaN,Claire Leinen
4,3/27/2025 14:39:04,Riley Mackey,Senior,5+ semesters,Yes,Yes,L Apartments,4th floor,Strongly Agree,Strongly Agree,...,Neutral,Neutral,Disagree,Agree,"Proximity to classes, Proximity to Wellness Ce...",Closeness to everything provided at a college ...,meal plan and the quality/cleanliness of the room,Neutral,NaN,Riley Mackey

In [7]:
df_2.head()

,Timestamp,What is your Class Status?,"Please type your name below to be entered into a gift card drawing for a chance to win a gift card to Target, Krispy Kreme, Taco Bell, and more! There are 5 chances to win! By submitting your name below you will receive an additional point for the 2023-2024 Housing Lottery.",How many semesters have you lived on campus at Grand View?,Are you currently 21 or older?,Do you participate on a Grand View Athletic team?,Which Residence Hall did you live in during the fall semester?,What floor did you live on during the fall semester?,Please read the following statements regarding your fall semester RA and rate them. [It is easy to get in contact with my RA],Please read the following statements regarding your fall semester RA and rate them. [I am comfortable talking with my RA],...,Please read the following statements regarding the outcome of living on campus and rate them. [I am a better problem solver because I have lived on campus],Please read the following statements regarding the outcome of living on campus and rate them. [I am better able to lead others because I have lived on campus],Please read the following statements regarding the outcome of living on campus and rate them. [I am better able to take responsibility for my actions because I have lived on campus],Please read the following statements regarding the outcome of living on campus and rate them. [Living on campus had a positive impact on my academic success],Please read the following statements regarding the outcome of living on campus and rate them. [Living on campus has created a sense of belonging at Grand View University],What are the main benefits of living on campus,What do you enjoy most about living on campus?,What do you dislike about living on campus?,How would you rate your overall satisfaction in regards to living on campus?,"Please type your name below to be entered into a gift card drawing for a chance to win a gift card to Target, Krispy Kreme, Taco Bell, and more! There are 5 chances to win! By submitting your name below you will receive an additional point for the 2023-2024 Housing Lottery..1"
0,1/29/2024 15:55:10,Junior,Olivia Brown,5+ Semesters,No,Yes,Hull Apartments,2nd Floor,Agree,Agree,...,Neutral,Neutral,Neutral,Agree,Agree,"Proximity to classes, Proximity to Wellness Ce...",Proximity,Parking,Satisfied,Olivia Brown
1,1/29/2024 17:28:48,Junior,Logan Skipton,3-4 Semesters,No,Yes,Hull Apartments,1st Floor,Neutral,Neutral,...,Neutral,Neutral,Neutral,Agree,Agree,"Proximity to classes, Proximity to Wellness Ce...",NaN,NaN,Satisfied,Logan Skipton
2,1/29/2024 17:31:14,Junior,Gabbie Roorda,5+ Semesters,No,Yes,Hull Apartments,2nd Floor,Strongly Agree,Strongly Agree,...,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,Strongly Agree,"Live within a community of peers, Proximity to...",NaN,NaN,Neutral,Gabbie Roorda
3,1/29/2024 18:05:30,Senior,Reghan Henn,5+ Semesters,Yes,Yes,Hull Apartments,3rd Floor,Strongly Agree,Strongly Agree,...,Agree,Agree,Neutral,Agree,Agree,"Proximity to classes, Live within a community ...",NaN,NaN,Satisfied,Reghan Henn
4,1/29/2024 20:46:58,Junior,Jesus Martinez-Aviles,1-2 Semesters,No,No,Hull Apartments,1st Floor,Strongly Agree,Strongly Agree,...,Agree,Agree,Agree,Agree,Agree,"Proximity to classes, Live within a community ...",i like having my own space and being close to ...,"i dont like the hours of some building, they c...",Satisfied,Jesus Martinez-Aviles